button_color = "black"
button_hover_color = "#404040"
text_color = "white"

[bar]
height = 32
font = "./assets/panel.ttf"

[[bar.buttons]]
text = "A"
command = "swaymsg kill"

[[bar.buttons]]
text = "B"
command = "swaymsg focus prev"

[[bar.buttons]]
text = "C"
command = "(echo A; echo B; echo C; echo D) | ./target/debug/ppkui_menu --config launcher.toml"

[[bar.buttons]]
text = "D"
command = "swaymsg focus next"

[[bar.buttons]]
text = "E"
command = "/home/alarm/toggle-keyboard.sh"
