height = 32
font = "/home/alarm/ppkui_bar/assets/panel.ttf"
button_color = "black"
button_hover_color = "#404040"
text_color = "white"

[[buttons]]
text = "A"
command = "swaymsg kill"

[[buttons]]
text = "B"
command = "swaymsg focus prev"

[[buttons]]
text = "C"
command = "/home/alarm/home_menu.sh"

[[buttons]]
text = "D"
command = "swaymsg focus next"

[[buttons]]
text = "E"
command = "/home/alarm/toggle-keyboard.sh"

